name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
    # 기존 fork시간설정: 매일정오 ("0 0 * * *")
    # 한 시간 간격 업데이트 설정함 ("0 * * * *")
    # 0 * * * *: 매 시간 0분에 실행
    # */30 * * * *: 매 30분마다 실행
    # 0 9 * * *: 매일 오전 9시에 실행
    # 0 0 * * 1-5: 평일(월요일부터 금요일까지) 자정에 실행
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TIMEZONE: Asia/Seoul
